### ISSUE TITLE
BigDecimal values being tracked and uploaded as String, not Number

### ISSUE THREAD

**Issue by chrismanderson** [segmentio/analytics-ruby#103]
We store money values in our database as decimal values, which Rails then treats as a BigDecimal in code. If I pass a BigDecimal value to the track calls, that value is passed into Segment as a string, not a number (in this case, `total` is a BigDecimal

```
Analytics.track(
    user_id: 1234,
    event: 'Purchased Item',
    properties: { total: order.total })
```

I can potentially convert the BigDecimal into a float before passing it into the `track` call; but generally, floats and currency are a bad combination.

So, how can I get a BigDecimal value into the tracking call without converting it to a float and potentially losing precision?

Thanks!

**Comment by f2prateek** [comment]
Could you share a more a concrete example? What does your BigDecimal look like and what is it's serialized representation? What does the loss in precision with the current behaviour look like?

**Comment by tonkapark** [comment]
So this caused problems for me recently so thought I'd share more information about what is happening here.

When you pass in a BigDecimal value in the parameters the [analytics request uses JSON.generate](https://github.com/segmentio/analytics-ruby/blob/master/lib/segment/analytics/request.rb#L44) which ultimately calls as_json on the BigDecimal object which returns a string. So that string is passed to Segment, which then passes that value as a string onto the final destination say in Keen.io or another reporting system. And now that number is a string and won't work in aggregate functions.

You will find there is some discussion around this [elsewhere](https://github.com/rails/rails/issues/25017) but I think for the use with event tracking you can simply convert to a float before passing the parameters hash to the Analytics.track method and everything works out if you require the value to be numeric when passed to the integrations connected to your Segment account.

**Comment by f2prateek** [comment]
Hey folks, sorry for the delay here, I thought I had replied but looks like I never did!

Unfortunately this is intentional - the reason is here is that our servers use Node.js under the hood. There are issues around parsing big numbers in Node which can cause them to lose precision.

In order to avoid losing precision, we convert these numbers to a string. This alleviates the issue of losing precision, however the issue here is then tools that accept the data in their raw format (like Keen.io or even our own warehouse destinations) will interpret them as strings instead of numbers (which can affect what kind of functions you can run on these).

I think the best thing we can do here is document this behaviour, and suggest an alternative - i.e. if you want to run aggregate functions on this data — send the data as a float which can be handled by node's json parsing code.

**Comment by f2prateek** [comment]
I've added a section to our docs about this behaviour.
