### ISSUE TITLE
Failed to pass the user_hash to Intercom

### ISSUE THREAD

**Issue by playpool513** [segmentio/analytics-ruby#156]
In order to verify users through Segment, Intercom suggested to [Add a new user_hash attribute to your analytics.identity function in your Segment JavaScript snippet with an HMAC code that you generate on your server](https://app.intercom.io/a/apps/_/guide/web_integration/web_integration_identity_verification): 
```
analytics.identify("<%= current_user.id %>", {
  …
}, {
  integrations: {
    Intercom : {
      user_hash : "<%= OpenSSL::HMAC.hexdigest("sha256", "user_hash_key", current_user.id) %>"
    }
  }
});
```

So I used this gem to create an event like this:
```
analytics.identify(
  user_id: profile.id, 
  integrations: { 
    Intercom: { 
      user_hash: user_hash 
    } 
  }, 
  traits: traits
)
```

The outputs are:

1. By using a gem called `httplog`, I can see that a request has been made:
```
[httplog] Connecting: api.segment.io:443
[httplog] Sending: POST http://api.segment.io:443/v1/import
[httplog] Data: {
  "sentAt": "2018-04-12T12:20:44.682+10:00",
  "batch": [
    {
      "userId": 31,
      "anonymousId": null,
      "integrations": {
        "Intercom": {
          "user_hash": "asdf..."
        }
      },
      "context": {
        "library": {
          "name": "analytics-ruby",
          "version": "2.2.2"
        }
      },
      "traits": {
        "email": "asdf...",
        ...
      }, 
      "options": null, 
      "messageId": "asdf...", 
      "timestamp": "2018-04-12T12:20:44.681+10:00", 
      "type": "identify"
    }
  ]
}
[httplog] Status: 200
[httplog] Benchmark: 0.193753 seconds
[httplog] Response:
{
  "success": true
}
```

2. The Raw View in Segment:
```
{
  "anonymousId": null,
  "context": {
    "library": {
      "name": "analytics-ruby",
      "version": "2.2.2"
    }
  },
  "integrations": {
    "Intercom": {
      "user_hash": "asdf..."
    }
  },
  "messageId": "asdf...",
  "timestamp": "2018-04-12T02:20:40.683Z",
  "traits": {
    "email": "asdf...",
    ...
  },
  "type": "identify",
  "userId": "31",
  "writeKey": "asdf...",
  "sentAt": "2018-04-12T02:20:44.682Z",
  "receivedAt": "2018-04-12T02:20:40.684Z",
  "originalTimestamp": "2018-04-12T12:20:44.681+10:00"
}
```

3. The Pretty view in Segment:
```
Analytics.identify(
  user_id: '31',
  traits: {
    email: 'asdf...',
    ...
  }
)
```

But Intercom didn't get the user_hash, and raised a `Missing user hashes` error.
I've asked Intercom for support, and they said they need to see the user_hash in the Pretty view as well before accepting any requests.

Please help me with this issue to pass the user_hash to Intercom.
Thanks.

**Comment by f2prateek** [comment]
hey @playpool513 - This doesn't appear to be an issue with the library itself, it's making the HTTP request as expected.

I suspect the issue is in either a) the Intercom integration or b) the way the ruby library is being invoked with the user hash.

Could you please write in to our support team and they can diagnose the issue from here https://segment.com/contact ?


PS - The hash doesn't need to be in the pretty view for destinations to receive it. The pretty view is just a prettified representation of the data - the raw view is the source of truth and the hash appears in the raw view.

**Comment by playpool513** [comment]
Hi @f2prateek,
Thanks for your quick reply and the declaration on pretty view and raw view.
Yes, I've written to Segment support team and Intercom support team for help.

**Comment by jeremyw** [comment]
@playpool513 I'm running into the same issue. Did you find a solution?

**Comment by f2prateek** [comment]
@jeremyw I don't think this is an issue with the library itself, but please write in the Segment support team for help!

**Comment by finaxar-arthur** [comment]
Was there any update to this?

**Comment by chris-keyplay** [comment]
For me, the issue was fixed when I updated the `Identify User` event mappings in Segment. The default mapping had an incorrect value for the User Hash field and when I updated that, the `Missing user hashes` error was resolved.

<img width="761" alt="Screen Shot 2023-10-05 at 10 45 17 PM" src="https://github.com/segmentio/analytics-ruby/assets/116021784/fcd8c97a-ce78-4b60-bcc1-24848df4c71a">

**Comment by kwent** [comment]
Same here except i defaulted to `traits.Intercom.userHash`

![Screenshot 2023-10-18 at 11 04 09 PM](https://github.com/segmentio/analytics-ruby/assets/879780/1408c8b4-5cda-4dcf-aeb8-8b32dcc2de95)
