### ISSUE TITLE
Add support for /delete request

### ISSUE THREAD

**Issue by ajsharp** [segmentio/analytics-ruby#165]
[This blog post](https://segment.com/blog/segment-and-the-gdpr/) describes support for a `/delete` request to delete a specific user's data:

> Support for deletion requests: We are making it easy for you to honor requests related to the right to be forgotten by adding a new, secure endpoint to our existing HTTP API: /delete. Issuing a /delete call for a given userId via this endpoint will ensure all personal data related to that userId is deleted from Segment's archives and your connected warehouses. 

This call doesn't appear to be supported in this library. Would you accept a PR supporting it?

**Comment by f2prateek** [comment]
hey @ajsharp , this is currently out of scope of the Ruby library due to the way the GDPR endpoint works. To echo what @sperand-io has mentioned;

https://github.com/segmentio/analytics-node/issues/169#issuecomment-385087032
```
Because the authentication scheme is different (deletes require a higher level of validation than a write-scoped key like our existing writekeys), we don't plan to add these requests to the existing data collection libs. Where as you can think of data collection as a synchronous-ish write to the Segment data plane, deletions are asynchronous jobs that you create through our management/control plane. (Docs are here: https://segment.com/docs/guides/best-practices/user-deletion-and-suppression/)

We're excited to make more of Segment (ie. not just data collection) programmatically addressable and to meet and set the standard for what it means to consume a pleasant API, with everything from auth to client libs and everything in between. On that front, stay tuned!
```

That being said, there are Node.js examples in https://segment.com/docs/guides/best-practices/user-deletion-and-suppression/ that should be under 100  lines of Ruby code as well.

Feel free to reach out to our support team if you need help https://segment.com/contact.
