### ISSUE TITLE
Getting UTM's 

### ISSUE THREAD

**Issue by rafaelmezzomo** [segmentio/analytics-ruby#70]
Hey Guys,

Please implement a way to mixpanel/google analytcs be able to receive UTM from the events we tracked.

**Comment by alexvbush** [comment]
hey guys, I'm in similar situation. Recently we've moved some of our sign up forms tracking from JS segment library to Ruby one so that when people sign up we can store email and other things in our own db and call tracking with some conditional logic on the backend. Unfortunately we don't have access to UTM params because of that.
Can you give a piece of advice on how to collect and submit UTM and other attributes (we need it for Mixpanel) and submit it to our backend so that Ruby library can pass those along to segment ?

**Comment by alexvbush** [comment]
currently we user ajax POST to pass the data but it could by anything. The main question is how to collect necessary utm, referrer, etc. data on JS side so that `analytics-ruby` has that data.
