### ISSUE TITLE
Pending Messages Lost When Process Exits

### ISSUE THREAD

**Issue by arielvalentin** [segmentio/analytics-ruby#95]
I am working on a Ruby application that currently logs all of its events in a background task. 
When working in "development" mode the system forks a new process, we then enqueue a few messages using and the program immediately exits. Unfortunately the [exit handler](https://github.com/segmentio/analytics-ruby/blob/f45eea0e1758c1ec64324271dc8e6bc669c1471b/lib/segment/analytics/client.rb#L30) is invoked and the [Worker thread](https://github.com/segmentio/analytics-ruby/blob/5efdfb7f2fc5f7751efebfa789e967ea99fd572e/lib/segment/analytics/worker.rb#L36) does not have an opportunity to process the messages, which results in the pending messages in the queue to be lost. 

Although I have not seen this in production I would assert that the problem would be true for any process that exits with pending messages in the queue.  

I am not sure what I want but I figured I would share this as a problem that I have experienced.

**Comment by alovak** [comment]
+1

require 'rubygems'
require 'bundler/setup'

Bundler.require(:default)

analytics = Segment::Analytics.new({
  write_key: 'xxx'
})

analytics.track(
    {
        user_id: 'bla',
        event: 'Processed Test Transaction'
    }
)

# without sleep it does not send data to segment...
sleep 5

**Comment by sperand-io** [comment]
Thanks for the flag! Apologies for the confusion here. Since the gem is async, you'll need to call `flush` (per the docs [here](https://segment.com/docs/libraries/ruby/#flush))

alternatively, you can use the community-maintained synchronous version for scripting/batch/queueing https://github.com/whatthewhat/simple_segment

holler here or via friends@segment.com if you run into any other issues!
